### ISSUE TITLE
The latest urkel tree update seems to be not synchronised 

### ISSUE THREAD

**Issue by handshake-enthusiast** [HNSDNS/docs#1]
Hey @LumitoLuma, thanks for HNSDNS! A regular user here.

Today I registered and updated .git, waited for on-chain DNS record changes to be effectuated and tried to check using HNSDNS:  
```
~
$ dig +short @139.144.68.241 git

~
$ dig +short @139.144.68.242 git

~
$ 
```

HNSDNS shows no DNS records while DNS servers from https://welcome.hnsdoh.com (by @Nathanwoodburn) show DNS records as expected:  
```
~
$ dig +short @194.50.5.26 git
35.154.209.88

~
$ dig +short @194.50.5.27 git
35.154.209.88

~
$ dig +short @194.50.5.28 git
35.154.209.88

~
$ 
```

**Comment by LumitoLuma** [comment]
Hello,

I have resynced my nodes and now everything should work as expected. Please check it and tell me if it works now.

Thanks for using HNSDNS,

Lumito.

**Comment by handshake-enthusiast** [comment]
Works, thanks!

```
~
$ dig +short @139.144.68.241 git
35.154.209.88

~
$ dig +short @139.144.68.242 git
35.154.209.88

~
$ 
```
